config/routes.rb
Rails.application.routes.draw do
  resources :marketplaces
  resources :menu_items
  root 'pages#home'

  devise_for :patrons
  resources :patrons, only: [:show]
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :patron
  belongs_to :role
end

app/models/marketplace.rb
class Marketplace < ApplicationRecord
  belongs_to :patron
  has_one_attached :image
  has_many :menu_items
  
  

  
  # only want business role to be able to post on market. when shown ideally would have prices with checkboxes and a checkout button

end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
    belongs_to :marketplace
end

app/models/patron.rb
class Patron < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_one :marketplace
         
    def patronname
      return self.email.split('@')[0]
   end
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :patrons, :join_table => :patrons_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) do |patron_params|
            patron_params.permit({ business_role: [] }, :email, :password, :password_confirmation)
        end
    end
    
end

app/controllers/marketplaces_controller.rb
class MarketplacesController < ApplicationController
  before_action :set_marketplace, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_patron!, except: [:show, :index]
  before_action :authorize, only: [:new, :edit, :create]

  # GET /marketplaces
  # GET /marketplaces.json
  def index
    @marketplaces = Marketplace.all
  end

  # GET /marketplaces/1
  # GET /marketplaces/1.json
  def show
    # @marketplace = Marketplace.find(params[:id])
    @menu_item = MenuItem.new
  end

  # GET /marketplaces/new
  def new
    @marketplace = Marketplace.new
  end

  # GET /marketplaces/1/edit
  def edit
  end

  # POST /marketplaces
  # POST /marketplaces.json
  def create
    @marketplace = Marketplace.new()
    @marketplace.patron = current_patron
    @marketplace.image.attach(params[:marketplace][:image])
    respond_to do |format|
      if @marketplace.save
          
        format.html { redirect_to @marketplace, notice: 'Marketplace was successfully created.' }
        format.json { render :show, status: :created, location: @marketplace }
      else
        format.html { render :new }
        format.json { render json: @marketplace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marketplaces/1
  # PATCH/PUT /marketplaces/1.json
  def update
    respond_to do |format|
      if @marketplace.update(marketplace_params)
        format.html { redirect_to @marketplace, notice: 'Marketplace was successfully updated.' }
        format.json { render :show, status: :ok, location: @marketplace }
      else
        format.html { render :edit }
        format.json { render json: @marketplace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marketplaces/1
  # DELETE /marketplaces/1.json
  def destroy
    @marketplace.destroy
    respond_to do |format|
      format.html { redirect_to marketplaces_url, notice: 'Marketplace was successfully destroyed.' }
      format.json { head :no_content }
      @post = current_patron.posts.find(params[:id])
      @post.destroy
      redirect_to patron_path(current_patron)
    end
  end

  private

  def authorize
      if !current_patron.has_role?(:admin)
        flash[:alert] = "Not Authorized."
        redirect_to marketplaces_url
  end

      #if patron not a business role cant post edit or delete anything, ideally wouldnt even be able to see the options
      #also only want business roles to be able to post once on marketplace with an image/bio/link back to thier profile which has the wares to purchase
  end
    # Use callbacks to share common setup or constraints between actions.
  def set_marketplace
    @marketplace = Marketplace.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def marketplace_params
    params.require(:marketplace).permit()
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/patrons_controller.rb
class PatronsController < ApplicationController

  def show
    @patron = Patron.find(params[:id])
  end

  def edit
     @patron = Patron.find(params[:id])
  end

  def update
    @patron = Patron.find(params[:id])
    if params[:patron][:business_role] == "1" 
    
    end
      @patron.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def has_role()

    end
end

app/helpers/marketplaces_helper.rb
module MarketplacesHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patrons_helper.rb
module PatronsHelper
end

app/views/layouts/_alerts.html.erb
<header class="navbar navbar-fixed-top nabvar-inverse">
    <div class="navbar-inner">
        <div class="container">
            <div class="navbar-header">
                <span><%= link_to "DiddysEats", root_path, id: "logo" %><span>
                <nav class="navbar">
                <ul class="nav navbar-nav navbar-right">
                    <p class="notice"><%= notice %></p>
                    <p class="alert"><%= alert %></p>
                </ul>
            </nav>
        </div>
    </div>
</header>

       

app/views/layouts/_footer.html.erb
<div id="push"></div>
    <footer class="footer navbar-fixed-bottom">
        <div class="container">
            <nav>
                <ul>
                    <li><%= link_to "home", root_path %></li>
                    <li><%= link_to "market", marketplaces_path %></li>
                
                </ul>
            </nav>
        </div>
    </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<stylesheet_link_tag "application.css">
  <head>
  
    <title>Diddyeats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%= render "layouts/alerts" %>

    <% if patron_signed_in? %>
      <a href=”<%= patron_path(current_patron)%>”>
        <i class=”fa fa-user”></i>
      </a>
    <% else %>
      <a href=”<%= new_patron_session_path%>”>
        <i class=”fa fa-sign-in”></i>
      </a>
    <% end %>
    </section>
   
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/marketplaces/_form.html.erb
<%= form_with(model: marketplace, local: true) do |form| %>
  <% if marketplace.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(marketplace.errors.count, "error") %> prohibited this marketplace from being saved:</h2>

      <ul>
        <%= marketplace.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= form.label :resertaunt %>
    <%= form.text_field :resteraunt %>
  </div class="field">
    <%= form.label :image %>
  <%= form.file_field :image, accept: 'image/png,image/jpeg,image/webp' %> 
  
  <div class="field">
    <%= form.label :bio %>
    <%= form.text_field :bio %>
  </div>

  <div class="actions">
    <%= form.submit %> 
  </div>
<% end %>

app/views/marketplaces/edit.html.erb
<h1>Editing Marketplace</h1>

<%= render 'form', marketplace: @marketplace %>

<%= link_to 'Show', @marketplace %> |
<%= link_to 'Back', marketplaces_path %>

app/views/marketplaces/index.html.erb
<h1>Marketplaces</h1>
<stylesheet_link_tag "marketplaces.scss">

  <tbody>
    <% @marketplaces.each do |marketplace| %>
      <table>
      <thead>
        <tr>
          
          <th>resteraunt </th>
          <th> Bio </th>
          <th colspan="3"></th>
        </tr>
      </thead>
      
      
        <td><%= marketplace.patron_id %></td>
        <td><%= link_to 'Show', marketplace %></td>
        
        <% if current_patron == current_patron.admin %> 
        <td><%= link_to 'Edit', edit_marketplace_path(@marketplace) %></td>
        <td><%= link_to 'Destroy', marketplace, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


<%= link_to 'Marketplaces', new_marketplace_path %>

app/views/marketplaces/show.html.erb
<p>
  <strong></strong>
  <%= @marketplace.patron.email.split("@")[0] %>
</p>
<% if @marketplace.image.attached? %>
  <%= image_tag @marketplace.image %> 
<% end %>

<h2>add an item</h2>
<%= form_with(model: @menu_item, local: true) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label :price %>
  <%= form.text_field :price %>

  
  <div class="actions">
  <%= form.submit %> 
</div>



<% end %>
  

<%= link_to 'edit', edit_marketplace_path(@marketplace) %>
<%= link_to 'Back', marketplaces_path %>

app/views/pages/home.html.erb
<h1>Welcome @patronname</h1>
<% if current_patron %>
<%= link_to "sign out", destroy_patron_session_path, method: :delete %>
<% else %>
<%= link_to "sign up", new_patron_registration_path %>

<%= link_to "sign in", new_patron_session_path %>
<% end %>
<%= link_to 'Marketplace', new_marketplace_path %>

app/views/patrons/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
    <% if profile.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
  
        <ul>
          <% profile.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div>
            <%= form.label "check this box if you are a resteraunt." %>
            <%= form.check_box_tag :business_role %>      
            # patron.role = "business_role" patron.save
    </div>
  
  
    <div class="actions">
        <%= form.submit "submit" %>
    </div>
  <% end %> 

app/views/patrons/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form', profile: @patron %>

<%= link_to 'Back', root_path %>

app/views/patrons/show.html.erb
<h1>@patron</h1>
<p>Find me in app/views/patrons/show.html.erb</p>
<div class="profile row">
  <div class="col-md-4 avatar">
    <!-- LEFT: AVATAR HERE -->
  </div>
  <div class="col-md-8 basic-info">
    <!-- RIGHT: USER INFORMATION HERE -->
  </div>
</div>
<div class="col-md-8 basic-info">
<div class="user-wrapper">
  <h2 class="username"></h2>
  <a class="edit-profile">
    <button>Edit Profile</button>
  </a>
</div>
<ul class="posts">
  <li><span>12</span> posts</li>
  <li><span>195</span> followers</li>
  <li><span>345</span> following</li>
</ul>
<h2 class="name"></h2>
<a class="website"></a>
</div>
</div>
</div>

<!-- <div class="patron-images">
  <% @patron posts.each do |post|%>
    <div class="wrapper">
      <%=link_to patron_path(patron) do %>
        <%=image_tag post.image %>
      <% end %>
    </div>
  <% end %>
</div> -->